### ISSUE TITLE
生成的视频越来越差，越来越失真

### ISSUE THREAD

**Issue by tianxiajianghu** [Vicky0522/I2VEdit#5]
大佬，生成的视频随着时间的延申，越来越差，越来越失真，是每个chunk视频都会采取上一段视频的最后一帧作为参考图吗，但是发现这个生成的参考图越来越差，导致视频内容变形，原理是什么，应该怎么调整
![image](https://github.com/user-attachments/assets/48cd8482-8d23-4f8e-b37e-cd59d1c8e9de)

**Comment by Vicky0522** [comment]
Errors tend to accumulate as the length of the edited video increases. Given that you are working with over 20 clips, it is likely that the output quality will degrade over such an extended duration.

**Comment by tianxiajianghu** [comment]
[item11_train.txt](https://github.com/user-attachments/files/18104708/item11_train.txt)
这是item11的训练脚本，你看看有什么问题吗？
![screenshot-20241212-102938](https://github.com/user-attachments/assets/8ac774a5-6b32-49fa-81b0-056ce1593ba8)
生成的视频转身衣服开始变化，和正面的衣服不一样了，转身之后就完全变化了，还有伪影

![clip_0_lastframe_0](https://github.com/user-attachments/assets/88e8d9a9-54c4-42d2-a509-e7cb0e4a35c5)
![clip_5_lastframe_0](https://github.com/user-attachments/assets/c038149f-3366-4fe3-bf43-dd9ed3c0e142)
![clip_7_lastframe_0](https://github.com/user-attachments/assets/8b3d8e34-6155-4ed5-bfc9-83f26fc96b48)

**Comment by Vicky0522** [comment]
<img width="495" alt="image" src="https://github.com/user-attachments/assets/df50be8e-2867-48ba-a8ab-06c9ce5199d3" />
Please exchange these parameters for the two editing cases. You can refer to the parameters used in the inference script on the hugging face page.

**Comment by tianxiajianghu** [comment]
https://github.com/user-attachments/assets/c7113a96-fc52-4e4d-a5bd-9ccc91e6736f
改好了之后，运动伪影没有了，但是中间的衣服变了，变成短袖了，颜色一致性也不行，不知道为什么结尾又好了

**Comment by tianxiajianghu** [comment]
改好了之后，运动伪影没有了，但是中间的衣服变了，变成短袖了，颜色一致性也不行，不知道为什么结尾又好了

https://github.com/user-attachments/assets/8ae06648-12b2-4566-86a5-3fbd12affd96

**Comment by Vicky0522** [comment]
Did you obtain the results by training the model from scratch, or did you use pre-existing data on the Hugging Face page?

**Comment by tianxiajianghu** [comment]
train the model from scratch.

**Comment by tianxiajianghu** [comment]
> Did you obtain the results by training the model from scratch, or did you use pre-existing data on the Hugging Face page?

train the model from scratch.

**Comment by Vicky0522** [comment]
I am not entirely certain about the exact cause, there may be some degree of randomness influencing the training outcomes. Since the motion "turn back" is particularly challenging, one possible explanation could be overfitting in the trained Motion LoRA for the clips featuring the woman turning back. To investigate further, you can review the validation results to identify any issues in the outputs. If problems are observed, you might consider retraining the Motion LoRA specifically for these clips and selecting a more suitable checkpoint for these cases.

**Comment by goo2go** [comment]
> I am not entirely certain about the exact cause, there may be some degree of randomness influencing the training outcomes. Since the motion "turn back" is particularly challenging, one possible explanation could be overfitting in the trained Motion LoRA for the clips featuring the woman turning back. To investigate further, you can review the validation results to identify any issues in the outputs. If problems are observed, you might consider retraining the Motion LoRA specifically for these clips and selecting a more suitable checkpoint for these cases.

by the way, why the clip data are so large in the pre-existing data on the Hugging Face page, it's too large

**Comment by 2hiTee** [comment]
> 改好了之后，运动伪影没有了，但是中间的衣服变了，变成短袖了，颜色一致性也不行，不知道为什么结尾又好了
> 
>  blue_dress.mp4

我猜测可能是给的编辑好的那一帧和背后视角相差太大，SVD模型可能无法把编辑效果spread到背后视角，所以无法编辑

**Comment by yoyoNTNU** [comment]
我想請問一下，我在嘗試使用`use_consistency_attention_control=true`並從頭開始訓練的時候，為什麼會出現`IndexError: list index out of range`，不論是在我的資料或是作者提供的範例都有這個問題

**Comment by Vicky0522** [comment]
> 我想請問一下，我在嘗試使用`use_consistency_attention_control=true`並從頭開始訓練的時候，為什麼會出現`IndexError: list index out of range`，不論是在我的資料或是作者提供的範例都有這個問題

Which item?

**Comment by yoyoNTNU** [comment]
> > 我想請問一下，我在嘗試使用`use_consistency_attention_control=true`並從頭開始訓練的時候，為什麼會出現`IndexError: list index out of range`，不論是在我的資料或是作者提供的範例都有這個問題
> 
> Which item?

item1
this is my log on item1 & my data
```
06/20/2025 11:55:40 - INFO - i2vedit.train - ***** Running training for motion lora*****
06/20/2025 11:55:40 - INFO - i2vedit.train -   Num examples = 1
06/20/2025 11:55:40 - INFO - i2vedit.train -   Num Epochs = 1
06/20/2025 11:55:40 - INFO - i2vedit.train -   Instantaneous batch size per device = 1
06/20/2025 11:55:40 - INFO - i2vedit.train -   Total train batch size (w. parallel, distributed & accumulation) = 1
06/20/2025 11:55:40 - INFO - i2vedit.train -   Gradient Accumulation steps = 1
06/20/2025 11:55:40 - INFO - i2vedit.train -   Total optimization steps = 1
Steps:   0%|                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]common_modules {}
find_modules {}
consistency_find_modules {'TemporalBasicTransformerBlock': ['attn1'], 'BasicTransformerBlock': []}
controller None consistency_controller <i2vedit.prompt_attention.attention_util.ConsistencyAttentionControl object at 0x0000025318BF9BB0>
Number of attention layer registered for controller: 0
Number of attention layer registered for consistency_controller: 16
Traceback (most recent call last):
  File "D:\project\I2VEdit\main.py", line 552, in <module>
    main(**OmegaConf.load(args.config))
  File "D:\project\I2VEdit\main.py", line 330, in main
    train_motion_lora(
  File "D:\project\I2VEdit\i2vedit\train.py", line 1266, in train_motion_lora
    loss_spatial, loss_temporal, latents, init_noise = finetune_unet(batch, step, mask_spatial_lora=mask_spatial_lora, mask_temporal_lora=mask_temporal_lora)
  File "D:\project\I2VEdit\i2vedit\train.py", line 1203, in finetune_unet
    model_pred = unet(
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\accelerate\utils\operations.py", line 822, in forward
    return model_forward(*args, **kwargs)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\accelerate\utils\operations.py", line 810, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\torch\amp\autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\diffusers\models\unet_spatio_temporal_condition.py", line 434, in forward
    sample, res_samples = downsample_block(
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\diffusers\models\unet_3d_blocks.py", line 2161, in forward
    hidden_states = attn(
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\diffusers\models\transformer_temporal.py", line 359, in forward
    hidden_states_mix = temporal_block(
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\diffusers\models\attention.py", line 509, in forward
    attn_output = self.attn1(norm_hidden_states, encoder_hidden_states=None)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\cgal\anaconda3\envs\i2vedit\lib\site-packages\diffusers\models\attention_processor.py", line 527, in forward
    return self.processor(
  File "D:\project\I2VEdit\i2vedit\prompt_attention\attention_register.py", line 87, in __call__
    key = self.consistency_controller(
  File "D:\project\I2VEdit\i2vedit\prompt_attention\attention_util.py", line 503, in __call__
    attn = self.forward(attn, is_cross, place_in_unet)
  File "D:\project\I2VEdit\i2vedit\prompt_attention\attention_util.py", line 538, in forward
    attn_base = step_in_store_atten_dict[key][current_pos].to(attn.device, attn.dtype)
IndexError: list index out of range
Steps:   0%|                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]
```

Maybe the config settings need to be changed?

**Comment by yoyoNTNU** [comment]
@Vicky0522 When i use the resolution 384x384, I will encounter this problem. Can you explain the relationship about resolution and consistency attention?

**Comment by Vicky0522** [comment]
I've attempted to reproduce the issues by training from scratch using the item1 config file available in the Hugging Face repository. My training completed successfully, and I haven't observed the reported issues. Can you provide your config file so I can investigate further?

> [@Vicky0522](https://github.com/Vicky0522) When i use the resolution 384x384, I will encounter this problem. Can you explain the relationship about resolution and consistency attention?

**Comment by yoyoNTNU** [comment]
Sure. This is my config file. My data resolution is square by the way, I'm not sure if that affects the whole process.
If possible, could you please try to edit a square video? Thanks for your time.
In my test, it can success edit square video for single chunk(w/o consistency attention), but multi-chunks will fail.
[config_multi_chunks.txt](https://github.com/user-attachments/files/20834490/config_multi_chunks.txt)

**Comment by Vicky0522** [comment]
Thank you for providing the config file. After my debugging, I've put together some tips for running with resolutions other than the default (e.g., 576 x 1024) used in the provided examples:

(1) For optimal performance, a resolution of 576 x 1024 is recommended, as SVD works best with this. Square videos can be padded and resized to this resolution by setting `pad_to_fit=true` in the config file. Please refer to item8 (the square video example). Using other resolutions may result in sub-optimal quality. 

(2) Some [code](https://github.com/Vicky0522/I2VEdit/blob/d26e002eb6b98de60ab8678537fb647c41760244/i2vedit/prompt_attention/attention_util.py#L467) for visualization purposes (but rarely used) causes errors with aspect ratios other than 16:9. This could be commented and modified as follows to support other aspect ratios:
```
#masks = rearrange(torch.cat(masks, 0), "b 1 (h w) 1 -> h (b w)", h=res*9)
masks = torch.cat(masks, 0)
```

(3) Currently, there's a bug that occurs when your training resolution matches the input video resolution. This can be fixed by changing the [code](https://github.com/Vicky0522/I2VEdit/blob/d26e002eb6b98de60ab8678537fb647c41760244/main.py#L313) as follows:
```
if consistency_train_controller is None:
    consistency_train_controller = consistency_store_controller
#consistency_train_controller = consistency_store_controller
```

If you successfully run the code, please let me know. I will push the fixes. Thanks for pointing this out.

> Sure. This is my config file. My data resolution is square by the way, I'm not sure if that affects the whole process. If possible, could you please try to edit a square video? Thanks for your time. In my test, it can success edit square video for single chunk(w/o consistency attention), but multi-chunks will fail. [config_multi_chunks.txt](https://github.com/user-attachments/files/20834490/config_multi_chunks.txt)

**Comment by yoyoNTNU** [comment]
Hi, @Vicky0522, thanks for your work, it's useful for me. Now I can edit the square video.
In my test on my local computer, it works fine, but in the huggingface space training, I encounter the same error https://github.com/Vicky0522/I2VEdit/issues/6#issuecomment-2538099755 , The `./trash` folder been removed, now I command the all of this code  and use `pass` skip this function, it works fine. https://github.com/Vicky0522/I2VEdit/blob/d26e002eb6b98de60ab8678537fb647c41760244/i2vedit/prompt_attention/attention_store.py#L222-L228
Hope this info can help you catch some bug.
In addition, I'd like to know why the default setting for the training resolution needs to be different from the input resolution?

thanks again. Best

**Comment by Vicky0522** [comment]
The error with the ./trash folder may be fixed by modifying the following code:
https://github.com/Vicky0522/I2VEdit/blob/d26e002eb6b98de60ab8678537fb647c41760244/i2vedit/prompt_attention/attention_util.py#L576
to
```
store_path:str=None
```
The codes in the train.py clean some temporary consistency controllers created during the training process to save disk storage. By modifying the above code, these temporary controllers will create individual folders under the ./trash folder instead of using ./trash itself, thereby avoiding removal errors. This doesn't happen when running the code locally, maybe because some written permission that restricts the removal process causes the removal failure. 

Due to GPU memory limitations, the default training resolution is currently set smaller than the input data's resolution. We've found this approach can also reduce overfitting in some cases. But it's not a strict requirement and can be adjusted if hardware or specific training changes.
