### ISSUE TITLE
Question about configuring `load_from_*` parameters in the config file

### ISSUE THREAD

**Issue by bbtty0423** [Vicky0522/I2VEdit#8]
Hello, I have successfully set up the environment and downloaded the required files using the following command:
```
huggingface-cli download Vicky0522/I2VEdit-pretrained-videos --include "item1/*" --repo-type=dataset --local-dir models
```
I have also downloaded the Stable Diffusion model and edited the config file accordingly. However, I’m not sure what values I should set for the following parameters in the config file:

- `load_from_last_frames_latents`
- `load_from_previous_consistency_edit_controller`
- `load_from_previous_consistency_store_controller`

I assume these parameters are intended to reference previously saved latents or consistency-related states from a previous run, but I’m uncertain about the exact file paths or directory structures that should be specified here. Additionally, I’m unsure about what values should be used if I’m running the process for the first time, i.e., when no previous data is available.

**My questions are:**

1. **What are these parameters supposed to point to?**  
   - For example, do they reference files created during a previous run that contain latent states or consistency controller information?

2. **What should I set these parameters to if I’m running the process for the first time and have no existing previous data?**  
   - Is it acceptable to set them to `None`, an empty string, or omit them entirely?

3. **If these files are expected to be included after running the `huggingface-cli download` command, can you clarify which specific files or directories they correspond to?**  
   - Any concrete example or reference would be greatly appreciated.

I’ve reviewed the documentation and existing issues but couldn’t find an example detailing these parameters. Any guidance on how to properly configure them would be very helpful. Thank you!

**Comment by Vicky0522** [comment]
For question 1, please refer to https://github.com/Vicky0522/I2VEdit?tab=readme-ov-file#reuse-data-for-subsequent-clips-based-on-previous-edits

For question 2, please refer to https://github.com/Vicky0522/I2VEdit?tab=readme-ov-file#customize-your-edits 

For question 3, after downloading the data as well as configuration files, just use the config file to test the items. Please refer to the instructions: https://github.com/Vicky0522/I2VEdit?tab=readme-ov-file#edit-pre-trained-videos

**Comment by bbtty0423** [comment]
Thank you for your response. I still haven’t resolved the issue. Below are the details of my environment.

I encountered a `FileNotFoundError` with the following steps:

1. Downloading the necessary files:
   ```bash
   huggingface-cli download Vicky0522/I2VEdit-pretrained-videos --include "item1/*" --repo-type=dataset --local-dir models
   ```

2. Applying the following diff to `config/customize_subsequent_edit.yaml` to create `config/customize_subsequent_edit item1.yaml`:
   ```diff
   diff --git a/config/customize_subsequent_edit item1.yaml b/config/customize_subsequent_edit item1.yaml
   index ad6b692..af82d3c 100644
   --- a/config/customize_subsequent_edit item1.yaml
   +++ b/config/customize_subsequent_edit item1.yaml
   @@ -1,5 +1,5 @@
    # Pretrained diffusers model path.
   -pretrained_model_path: "ckpts/stable-video-diffusion-img2vid"
   +pretrained_model_path: "~/.cache/huggingface/hub/models--stabilityai--stable-video-diffusion-img2vid"
    # The folder where your training outputs will be placed.
    output_dir: "./acc"
    seed: 23
   @@ -35,10 +35,10 @@ load_from_previous_consistency_store_controller:
    
    # data_params
    data_params:
   -  video_path: "../datasets/svdedit/item1/source.mp4"
   +  video_path: "./models/item1/source_and_edits/source.mp4"
      keyframe_paths:
   -    - "../datasets/svdedit/tmp/edit0.png"
   -    - "../datasets/svdedit/tmp/edit1.png"
   +    - "./models/item1/source_and_edits/white_sculpture.png"
   +    - "./models/item1/source_and_edits/necklace.png"
      start_t: 0
      end_t: -1
      sample_fps: 7
   @@ -112,11 +112,11 @@ attention_matching_params:
      best_checkpoint_index: 250
      lora_scale: 1.0
      # lora path
   -  lora_dir: ~
   +  lora_dir: "./models/item1/train_motion_lora"
      max_guidance_scale: 2.0
      disk_store: True
   -  load_attention_store: "./cache/item1/attention_store"
   -  load_consistency_attention_store: ~
   +  load_attention_store: "./models/item1/attention_store"
   +  load_consistency_attention_store: "./models/item1/consistency_attention_store"
      registered_modules:
        BasicTransformerBlock:
          - "attn1"
   ```

3. Running the command:
   ```bash
   CUDA_VISIBLE_DEVICES=3 python main.py --config "config/customize_subsequent_edit item1.yaml"
   ```

4. The error encountered:
   ```
   FileNotFoundError: [Errno 2] No such file or directory: './cache/item1/i2vedit_2024-05-11T15-53-54/clip_0_lastframe_0.pt'
   ```

Any advice would be greatly appreciated.

**Comment by bbtty0423** [comment]
Furthermore, if I comment out the lines related to `load_from_last_frames_latents`, `load_from_previous_consistency_edit_controller`, and `load_from_previous_consistency_store_controller` in the config, I encounter the following error:

```
Traceback (most recent call last):
  File "~/work/I2VEdit/main.py", line 552, in <module>
    main(**OmegaConf.load(args.config))
  File "~/work/I2VEdit/main.py", line 541, in main
    print("consistency_store_controller for clip 0:", previous_consistency_store_controller.store_dir) 
AttributeError: 'NoneType' object has no attribute 'store_dir'
```

**Comment by bbtty0423** [comment]
I seem to have been referencing the wrong config file.  
After downloading the dataset with the following command and checking the correct config file:  
```
huggingface-cli download Vicky0522/I2VEdit-pretrained-videos --include "item1/*" --repo-type=dataset --local-dir models
```
it appears that the config file to use should be `models/item1/config_*_chunk.yaml`.  
However, using this file results in the following error related to `pretrained_model_path`:

```
Traceback (most recent call last):
  File "~/miniconda3/envs/i2vedit/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 376, in load_config
    config_file = hf_hub_download(
  File "~/miniconda3/envs/i2vedit/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "~/miniconda3/envs/i2vedit/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '~/work/I2VEdit/stable-video-diffusion-img2vid'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/work_tmp/work/I2VEdit/main.py", line 552, in <module>
    main(**OmegaConf.load(args.config))
  File "~/work_tmp/work/I2VEdit/main.py", line 364, in main
    pipe = initialize_pipeline(
  File "~/work_tmp/work/I2VEdit/i2vedit/inference.py", line 37, in initialize_pipeline
    scheduler, feature_extractor, image_encoder, vae, unet = load_primary_models(model)
  File "~/work_tmp/work/I2VEdit/i2vedit/train.py", line 136, in load_primary_models
    noise_scheduler = EulerDiscreteScheduler.from_pretrained(
  File "~/miniconda3/envs/i2vedit/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "~/miniconda3/envs/i2vedit/lib/python3.9/site-packages/diffusers/schedulers/scheduling_utils.py", line 142, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "~/miniconda3/envs/i2vedit/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "~/miniconda3/envs/i2vedit/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 411, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ~/work/I2VEdit/stable-video-diffusion-img2vid is not the path to a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
```

Also, I obtained the diffusion model as follows:
```
git clone https://huggingface.co/stabilityai/stable-video-diffusion-img2vid
cd stable-video-diffusion-img2vid
git lfs pull
```

Could you advise on how to correctly specify `pretrained_model_path` or how to properly handle the local path in this situation?

**Comment by Vicky0522** [comment]
It appears that the directory `~/work/I2VEdit/stable-video-diffusion-img2vid` either does not exist or is missing some required files. You might verify that the directory is present and that all necessary files are included before attempting to load the weights.
